# Generated by Django 2.2.5 on 2019-10-02 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('info', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('info', models.TextField(blank=True, default='')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genus',
                'verbose_name_plural': 'Genera',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('text', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(default='')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('info', models.TextField(blank=True, default='')),
                ('epithet', models.CharField(blank=True, default='', max_length=50, verbose_name='species epithet')),
                ('authorship', models.CharField(blank=True, default='', max_length=50)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.Genus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, upload_to='title_images/')),
                ('caption', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesSynonim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_table', models.CharField(choices=[('N', 'Normal'), ('A', 'Advanced')], default='N', max_length=1)),
                ('from_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='flora.Species')),
                ('to_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='flora.Species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='synonym',
            field=models.ManyToManyField(related_name='_species_synonym_+', through='flora.SpeciesSynonim', to='flora.Species'),
        ),
        migrations.AddField(
            model_name='species',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(blank=True, default='')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'flora'), ('model', 'family')), models.Q(('app_label', 'flora'), ('model', 'genus')), models.Q(('app_label', 'flora'), ('model', 'species')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(default='', max_length=500)),
                ('url', models.URLField(default='', max_length=500)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'flora'), ('model', 'family')), models.Q(('app_label', 'flora'), ('model', 'genus')), models.Q(('app_label', 'flora'), ('model', 'species')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
