# Generated by Django 2.2.5 on 2019-09-29 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('info', models.TextField(blank=True, default='')),
                ('family', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ('family',),
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('info', models.TextField(blank=True, default='')),
                ('genus', models.CharField(default='', max_length=50)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Genus',
                'verbose_name_plural': 'Genuses',
                'ordering': ('genus',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('text', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(default='')),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, upload_to='title_images/')),
                ('caption', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rarity', models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Endanger'), ('V', 'Vanishing')], default='R', max_length=1, null=True)),
                ('info', models.TextField(blank=True, default='')),
                ('epithet', models.CharField(blank=True, default='', max_length=50, verbose_name='species epithet')),
                ('authorship', models.CharField(blank=True, default='', max_length=50)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flora.Genus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, default='')),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Family')),
                ('genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Genus')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('url', models.URLField(default='', max_length=500)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Family')),
                ('genus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Genus')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flora.Species')),
            ],
        ),
    ]
