# Generated by Django 2.2.5 on 2019-09-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesSynonim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_table', models.CharField(choices=[('N', 'Normal'), ('A', 'Advanced')], default='N', max_length=1)),
                ('from_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='flora.Species')),
                ('to_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='flora.Species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='synonym',
            field=models.ManyToManyField(related_name='_species_synonym_+', through='flora.SpeciesSynonim', to='flora.Species'),
        ),
    ]
