# Generated by Django 2.2.5 on 2019-10-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_auto_20191002_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ('name',), 'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'ordering': ('name',), 'verbose_name': 'Genus', 'verbose_name_plural': 'Genera'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('genus__name', 'name')},
        ),
    ]
