# Generated by Django 2.2.5 on 2019-10-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0003_auto_20191002_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='abbr',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
