# Generated by Django 2.2.5 on 2019-10-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0004_occurrence_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciessynonim',
            name='synonym_table',
            field=models.CharField(choices=[('K', 'Kharkevich'), ('Q', 'QIAN')], default='N', max_length=1),
        ),
    ]
