# Generated by Django 2.2.5 on 2022-07-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='abbr',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
